### ISSUE TITLE
Hi, I`m from youtube

### ISSUE THREAD

**Issue by Alex19911638641** [herisulistiyanto/weather-melody#1]
Halo, nama saya Alex, saya dari Rusia
Hello, my name is Alex, I'm from Russia

Saya sangat menyukai bagaimana Anda melakukan lagu "See You Again" di "studio FL"
I really liked how you did the song "See You Again" in "FL studio"

Deskripsinya adalah link, tapi tidak berfungsi lagi
The description there was a link, but it does not work anymore

Bisakah Anda mengupload file format FLP lagi dan mengirimkannya ke e-mail saya?
Could you upload the FLP format file again and send it to my e-mail?

it is desirable to post deadline_production@mail.ru :))

Saya akan sangat berterima kasih kepada Anda
I would be very grateful to you

**Comment by herisulistiyanto** [comment]
Hi @Alex19911638641 
sorry for late response
i already reupload the project, and now in ZIP (including drum pack & vocal acapella)
[youtube link](https://www.youtube.com/watch?v=KieUMvoVM70)
Thanks
